### ISSUE TITLE
Facing Issue with getcurrentSlide()

### ISSUE THREAD

**Issue by KaushikRay** [netgfx/PhaseSlider#2]
Hi, Thanks for the plugin.
One issue - whenever I try to get current slide number in prev or next callback, i get wrong slide numbers.

Code - 
`onPrevCallback: function(){
        window.console.log("prev");
          var index = slider.getCurrentIndex();`

Same for next. Any idea? Thanks

**Comment by netgfx** [comment]
how many slider indexes off? +-1 or more?

**Comment by KaushikRay** [comment]
sometimes it is more than 1. I think I got the reason but not sure how to solve same?
onprevcallback and onnextcallback code gets called much earlier that the library code can execute. So basically it is always giving me the number of last slide I was in.

so
it gives the value in nextcallback as 0 which is current slide I am on in and not the next one. phase-slide.js code gets executed after this - 

phase-slider.js:60 slide index before 0
phase-slider.js:62 slide index after 1

**Comment by netgfx** [comment]
hm I see what the problem is, this is due to the following code:

```
if (_this.options._onNextCallback) {
                        _this.options._onNextCallback();
                    }

                    if (_this.tweenObj.isRunning !== true) {
                        _this.stopSlider();
                        _this.goToNext();
                    }
```
As you see the `onNextCallback` gets called before the `goToNext` function
So this serves as a `pre-move-to-next-slide` and not as a `after-move-to-next-slide` as you thought and probably wanted.
So this is not a bug but rather a new feature.

I will try to add another callback one for `pre-move` and one for `after-move` so that users can use whatever suits their needs.
