### ISSUE TITLE
Is there an easy option to control the size of the slide?

### ISSUE THREAD

**Issue by Mikewa33** [netgfx/PhaseSlider#4]
Looking at having multiple objects in one selection and then left and right loads in a new one. Say I want to display 5 objects at once. Is there an easy param to set? Also should this work with phaser 3?

**Comment by netgfx** [comment]
@Mikewa33 If you pass a Sprite with multiple objects inside as 1st or nth element or a Group it will display all of them on one slide, you just have to pre-group them before you pass them to the config object of the plugin.
Not it won't work with Phaser 3 because the plugin and general architecture of Phaser 3 is very different than Phaser 2. 
But I might consider making another plugin for Phaser 3

**Comment by Mikewa33** [comment]
> @Mikewa33 If you pass a Sprite with multiple objects inside as 1st or nth element or a Group it will display all of them on one slide, you just have to pre-group them before you pass them to the config object of the plugin.
> Not it won't work with Phaser 3 because the plugin and general architecture of Phaser 3 is very different than Phaser 2. 
> But I might consider making another plugin for Phaser 3

Thanks for the quick reply and the info!
